import { useEffect, useState } from "react";

const API = "http://localhost:5000/api";
const SEV_COLOR = { Critical: "#ef4444", High: "#f97316", Medium: "#eab308", Low: "#22c55e" };

export default function Alerts() {
  const [alerts, setAlerts] = useState([]);
  const [filter, setFilter] = useState({ severity: "All", type: "All", status: "All" });

  const load = () => {
    fetch(`${API}/alerts`).then(r => r.json()).then(setAlerts).catch(() => {});
  };

  useEffect(() => { load(); }, []);

  const resolve = async (id) => {
    await fetch(`${API}/alerts/${id}/resolve`, { method: "PUT" });
    load();
  };

  const filtered = alerts.filter(a =>
    (filter.severity === "All" || a.severity === filter.severity) &&
    (filter.type === "All" || a.type === filter.type) &&
    (filter.status === "All" || a.status === filter.status)
  );

  const FilterBtn = ({ label, field, value }) => (
    <button onClick={() => setFilter(f => ({ ...f, [field]: value }))} style={{
      padding: "6px 14px", borderRadius: 20, border: "none", cursor: "pointer", fontSize: 12,
      background: filter[field] === value ? "#1a2744" : "#0d1220",
      color: filter[field] === value ? "#4a90e2" : "#64748b",
    }}>{label}</button>
  );

  return (
    <div>
      <div style={{ marginBottom: 28 }}>
        <div style={{ fontSize: 11, color: "#4a90e2", letterSpacing: 3, marginBottom: 8 }}>LIVE SOC VIEW</div>
        <h2 style={{ fontSize: 26, fontWeight: 800, color: "#f1f5f9", margin: 0 }}>🚨 Alert Dashboard</h2>
        <p style={{ color: "#64748b", marginTop: 8 }}>All IOA and IOM alerts generated by the detection engine. Run simulations from the Best Practice pages to populate alerts.</p>
      </div>

      {/* Filters */}
      <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 24 }}>
        <span style={{ fontSize: 11, color: "#475569", alignSelf: "center" }}>SEVERITY:</span>
        {["All", "Critical", "High", "Medium", "Low"].map(v => <FilterBtn key={v} label={v} field="severity" value={v} />)}
        <span style={{ fontSize: 11, color: "#475569", alignSelf: "center", marginLeft: 8 }}>TYPE:</span>
        {["All", "IOA", "IOM"].map(v => <FilterBtn key={v} label={v} field="type" value={v} />)}
        <span style={{ fontSize: 11, color: "#475569", alignSelf: "center", marginLeft: 8 }}>STATUS:</span>
        {["All", "Open", "Resolved"].map(v => <FilterBtn key={v} label={v} field="status" value={v} />)}
      </div>

      {/* Count */}
      <div style={{ fontSize: 12, color: "#475569", marginBottom: 16 }}>
        Showing {filtered.length} of {alerts.length} alerts
      </div>

      {/* Alert List */}
      {filtered.length === 0 ? (
        <div style={{ textAlign: "center", padding: 60, color: "#334155" }}>
          <div style={{ fontSize: 32, marginBottom: 12 }}>🔍</div>
          <div style={{ fontSize: 16, fontWeight: 600 }}>No alerts yet</div>
          <div style={{ fontSize: 13, marginTop: 8 }}>Run a simulation from any Best Practice page to generate alerts.</div>
        </div>
      ) : (
        <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
          {filtered.map(alert => (
            <div key={alert.id} style={{
              background: "#0d1220",
              border: `1px solid ${alert.status === "Resolved" ? "#1e2d45" : (SEV_COLOR[alert.severity] + "44")}`,
              borderRadius: 10, padding: "16px 20px",
              opacity: alert.status === "Resolved" ? 0.6 : 1,
            }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
                <div style={{ flex: 1 }}>
                  <div style={{ display: "flex", gap: 8, alignItems: "center", marginBottom: 6 }}>
                    <span style={{
                      fontSize: 10, padding: "2px 10px", borderRadius: 20,
                      background: `${SEV_COLOR[alert.severity]}22`, color: SEV_COLOR[alert.severity], fontWeight: 700,
                    }}>{alert.severity}</span>
                    <span style={{ fontSize: 10, padding: "2px 10px", borderRadius: 20, background: "#1e2d45", color: "#64748b" }}>{alert.type}</span>
                    <span style={{ fontSize: 10, padding: "2px 10px", borderRadius: 20, background: alert.status === "Open" ? "#ef444422" : "#22c55e22", color: alert.status === "Open" ? "#ef4444" : "#22c55e" }}>{alert.status}</span>
                  </div>
                  <div style={{ fontSize: 15, fontWeight: 700, color: "#e2e8f0", marginBottom: 6 }}>{alert.title}</div>
                  <div style={{ fontSize: 12, color: "#64748b" }}>{alert.description}</div>
                  <div style={{ fontSize: 11, color: "#334155", marginTop: 6 }}>{alert.timestamp}</div>
                </div>
                {alert.status === "Open" && (
                  <button onClick={() => resolve(alert.id)} style={{
                    marginLeft: 16, padding: "6px 14px", borderRadius: 6, border: "1px solid #22c55e44",
                    background: "transparent", color: "#22c55e", fontSize: 12, cursor: "pointer",
                    flexShrink: 0,
                  }}>✓ Resolve</button>
                )}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
