"""
models/alert.py
---------------
Defines what ONE alert looks like as a Python object.

Alerts are generated by the detection engine (services/detection.py)
when a Log's action matches an IOA or IOM rule.

Fields:
  type           : "IOA" (runtime attack) or "IOM" (misconfiguration)
  severity       : Critical / High / Medium / Low
  best_practice  : 1–5 → maps to the CrowdStrike CDR best practice
  mitre_technique: e.g. T1484.001
  related_log_id : FK → cloud_logs.id (which log triggered this alert)
"""

from dataclasses import dataclass, asdict


@dataclass
class Alert:
    # Core fields
    type:            str
    severity:        str
    title:           str
    description:     str
    timestamp:       str

    # Context
    status:          str  = "Open"
    related_log_id:  int  = 0
    best_practice:   int  = 0
    mitre_technique: str  = ""
    mitre_tactic:    str  = ""

    # DB-assigned
    id:              int  = 0

    def to_dict(self) -> dict:
        """Convert to plain dict for JSON serialisation."""
        return asdict(self)

    @staticmethod
    def from_row(row) -> "Alert":
        """
        Build an Alert from a sqlite3.Row.
        Used when reading alerts back from the database.
        """
        return Alert(
            id              = row["id"],
            type            = row["type"],
            severity        = row["severity"],
            title           = row["title"],
            description     = row["description"],
            timestamp       = row["timestamp"],
            status          = row["status"]          or "Open",
            related_log_id  = row["related_log_id"]  or 0,
            best_practice   = row["best_practice"]   or 0,
            mitre_technique = row["mitre_technique"] or "",
            mitre_tactic    = row["mitre_tactic"]    or "",
        )