-- ============================================================
-- CloudGuard Schema
-- ============================================================
-- Run once via database.py init_db().
-- All CREATE TABLE statements use IF NOT EXISTS so re-running
-- is safe and idempotent.
-- ============================================================


-- ── CLOUD LOGS ──────────────────────────────────────────────
-- Simulated CloudTrail-style API events.
-- is_malicious : 1 = attacker action  |  0 = normal/benign
-- mitre_technique : e.g. T1078.004
-- mitre_tactic    : e.g. Initial Access
CREATE TABLE IF NOT EXISTS cloud_logs (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp       TEXT    NOT NULL,
    user            TEXT    NOT NULL,
    action          TEXT    NOT NULL,
    source_ip       TEXT,
    region          TEXT,
    cloud_service   TEXT,
    severity        TEXT    CHECK(severity IN ('Critical','High','Medium','Low')),
    is_malicious    INTEGER DEFAULT 0 CHECK(is_malicious IN (0,1)),
    scenario_id     INTEGER DEFAULT 0,
    mitre_technique TEXT    DEFAULT '',
    mitre_tactic    TEXT    DEFAULT ''
);


-- ── ALERTS ──────────────────────────────────────────────────
-- Generated by the IOA/IOM detection engine.
-- type         : IOA (runtime behaviour) | IOM (misconfiguration)
-- best_practice: 1–5, maps to CrowdStrike CDR best practices
CREATE TABLE IF NOT EXISTS alerts (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    type            TEXT    NOT NULL CHECK(type IN ('IOA','IOM')),
    severity        TEXT    NOT NULL CHECK(severity IN ('Critical','High','Medium','Low')),
    title           TEXT    NOT NULL,
    description     TEXT    NOT NULL,
    timestamp       TEXT    NOT NULL,
    status          TEXT    DEFAULT 'Open' CHECK(status IN ('Open','Resolved')),
    related_log_id  INTEGER REFERENCES cloud_logs(id),
    best_practice   INTEGER DEFAULT 0,
    mitre_technique TEXT    DEFAULT '',
    mitre_tactic    TEXT    DEFAULT ''
);


-- ── ATTACK SCENARIOS ────────────────────────────────────────
-- Seeded once. Never cleared by reset.
CREATE TABLE IF NOT EXISTS attack_scenarios (
    id                      INTEGER PRIMARY KEY,
    name                    TEXT NOT NULL,
    description             TEXT NOT NULL,
    attack_vector           TEXT NOT NULL,
    layer_targeted          TEXT NOT NULL,
    best_practice_violated  TEXT NOT NULL,
    mitre_tactics           TEXT NOT NULL
);